### ISSUE TITLE
Console error

### ISSUE THREAD

**Issue by joaoferraaz** [schwim0341/esx_trunk#1]
![image](https://user-images.githubusercontent.com/37892381/56523427-d6942200-651d-11e9-8fde-97cf47dc6198.png)
you can help me?

**Comment by schwim0341** [comment]
Give 1.0.3 a shot.

https://github.com/schwim0341/esx_trunk/releases/tag/1.0.3

**Comment by joaoferraaz** [comment]
Thanks ! <3
