### ISSUE TITLE
Trunk Ignores Inventory Limits

### ISSUE THREAD

**Issue by Janicki92** [schwim0341/esx_trunk#14]
Having an issue where players can deposit the "max" they can hold into their trunk, repeat that process, and then retrieve more than they're supposed to be able to hold.

Example:  Player is out farming weed.  He can only hold 50 "buds".  He deposits the 50 buds into his trunk.  He farms 50 more buds, depositing into his trunk, equaling 100 buds in his trunk.

He then goes to process these "buds" and can retrieve all 100, ignoring the 50 item limit set in the database.  Same applies when they go to sell, etc.

**Comment by schwim0341** [comment]
It's a known issue which will get resolved one day.. probably.

**Comment by Modatherrr** [comment]
Same here, hope it get fixed soon. and sure thanks Schwim for this nice mod.

**Comment by Janicki92** [comment]
Same.   And again, thanks for this awesome script Schwim!

________________________________

**Comment by noobiiz** [comment]
Same ^^"

**Comment by schwim0341** [comment]
Same << >> ^^ << >>

**Comment by Summerxo** [comment]
server\esx_trunk-sv.lua

```
RegisterServerEvent('esx_trunk:getItem')
AddEventHandler('esx_trunk:getItem', function(plate, type, item, count, itemName)

  local _source      = source
  local xPlayer      = ESX.GetPlayerFromId(_source)
  local sourceItem = xPlayer.getInventoryItem(item)

  if type == 'item_standard' then

    TriggerEvent('esx_trunk:getSharedDataStore', plate, function(store)
      local coffre = (store.get('coffre') or {})
      for i=1, #coffre,1 do
        if coffre[i].name == item then
          if (coffre[i].count >= count and count > 0) then
            if sourceItem.limit ~= -1 and ((sourceItem.count + count) > sourceItem.limit) then
               TriggerClientEvent('esx:showNotification', _source, _U('player_cannot_hold')) 
            else
            xPlayer.addInventoryItem(item, count)
            if (coffre[i].count - count) == 0 then
              table.remove(coffre,i)
            else
              coffre[i].count = coffre[i].count - count
            end
          end
            break
          else
            TriggerClientEvent('esx:showNotification', _source, _U('invalid_quantity'))
          end
        end
      end
```


There you go. Oh in the locales. add    ['player_cannot_hold']   = 'You can not hold anymore of this.',

Last edit to get the dupes/bugs out of it. Cheers.
