### ISSUE TITLE
esx_trunk high tick

### ISSUE THREAD

**Issue by lucasvperini** [schwim0341/esx_trunk#15]
Hey,

I've just made a trace on my resources and saw that esx_trunk is getting 167ms on tick.
![image](https://user-images.githubusercontent.com/47780889/58198884-a7e8a300-7ca5-11e9-964d-4ddb03db36de.png)
I'm using the latest version of all scripts/artifacts.
Any ideas?

Thanks.

**Comment by schwim0341** [comment]
Not sure, can't duplicate on my client. If you find the problem loop, be sure to share.

![image](https://user-images.githubusercontent.com/15654144/58199734-2d1c8980-7c9f-11e9-8d25-6937e803f285.png)

**Comment by lucasvperini** [comment]
Idk if this helps, but i'm getting this error on console:

`Error running system event handling function for resource esx_trunk: citizen:/scripting/lua/scheduler.lua:41: Failed to execute thread: @esx_trunk/server/trunk.lua:47: bad argument #1 to 'find' (string expected, got nil)stack traceback:
        [C]: in function 'string.find'
        @esx_trunk/server/trunk.lua:47: in function 'getOwnedVehicule'
        @esx_trunk/server/trunk.lua:76: in function 'MakeDataStore'
        @esx_trunk/server/trunk.lua:91: in function 'GetSharedDataStore'
        @esx_trunk/server/trunk.lua:97: in upvalue 'handler'
        citizen:/scripting/lua/scheduler.lua:219: in function <citizen:/scripting/lua/scheduler.lua:218>stack traceback:
        [C]: in function 'error'
        citizen:/scripting/lua/scheduler.lua:41: in field 'CreateThreadNow'
        citizen:/scripting/lua/scheduler.lua:218: in function <citizen:/scripting/lua/scheduler.lua:182>
        [C]: in function 'coroutine.resume'
        citizen:/scripting/lua/scheduler.lua:34: in field 'CreateThreadNow'
        citizen:/scripting/lua/scheduler.lua:389: in function <citizen:/scripting/lua/scheduler.lua:374>`

This helps somehow?

Thanks.

**Comment by gmorellop** [comment]
Mine getting high tick too .

**Comment by lucasvperini** [comment]
Any news?

**Comment by fluidsc** [comment]
Just to throw a bit of something into this... I play on a server using the following script:

https://forum.fivem.net/t/addon-esx-inventory-hud-vehicle-trunk/458152

I doubt it is the same script, but it probably has a very similar data table layout. They started having MAJOR issues with server lag, server death, and needing to restart once the server was populated. What was found was that people were abusing the trunk system and using it as "personal & permanent storage".

If this admin has the same issue, that could be causing his high tick count.

**Comment by schwim0341** [comment]
He based it off of this one so it very well could be the same issue.

**Comment by noobiiz** [comment]
![image](https://user-images.githubusercontent.com/3207202/63117817-89273f00-bf6a-11e9-8058-4309c0f42903.png)
Same here :/

**Comment by Jhudri** [comment]
try removing all the "print statements" on the client side. --PRINT
