### ISSUE TITLE
esx_trunk works but not fully

### ISSUE THREAD

**Issue by Hobbit2811** [schwim0341/esx_trunk#26]
We can place out Items in it, guns etc. but we cant take out items out like stones etc. only weapons work when trying to take anything out... i worked the last week to find the error but im unable too any suggestions to a new trunk system or a fix?

**Comment by Goontje** [comment]
> We can place out Items in it, guns etc. but we cant take out items out like stones etc. only weapons work when trying to take anything out... i worked the last week to find the error but im unable too any suggestions to a new trunk system or a fix?

Same here! cannot take out anything besides weapons.
Still no fix..

**Comment by schwim0341** [comment]
What version of ESX are you using?

**Comment by Goontje** [comment]
> What version of ESX are you using?

Latest of V1

**Comment by lucaherzog** [comment]
Its not working for me also.

**Comment by schwim0341** [comment]
trunk will be updated for the next version of sesx which is being built now.  I'll update the issues when it's ready.

**Comment by schwim0341** [comment]
fixt.
