### ISSUE TITLE
How can i open the menu?

### ISSUE THREAD

**Issue by Mariox6** [schwim0341/esx_trunk#5]

**Comment by KrizKhaoz** [comment]
When you press the button nothing appears trunk opens no menu.

**Comment by schwim0341** [comment]
Can not duplicate and it's working fine for Discord support.  Without any troubleshooting info at all, this is a non-starter.

**Comment by Mariox6** [comment]
Can you try? It doesn´t work ;(
https://anonfile.com/B4P4m4i4n2/esx_trunk_rar

**Comment by Mariox6** [comment]
Or can you send me your version, because the version on github doesn´t work for me

**Comment by schwim0341** [comment]
Check version 2 guys.  It's a complete alteration, SQL is not compatible so keep that in mind.
