### ISSUE TITLE
Job vehicles

### ISSUE THREAD

**Issue by lucasvperini** [schwim0341/esx_trunk#6]
Hey!

It's possible to whitelist cars where players can open the trunk?
For example, the gang members can't open gang cars trunk, because they're not the owners...

Any ideas?

Thanks!

**Comment by schwim0341** [comment]
There is no capability to whitelist vehicles for certain people.

**Comment by Agony099** [comment]
Going off of that is there a way to unlock\whitelist ALL job vehicles?

**Comment by schwim0341** [comment]
The script works off of plate and ownership.  You can turn off ownership if you'd like as it's written or you can modify the check to do whatever you'd like with particular vehicles.

**Comment by omarabbaas** [comment]
any solution for this problem ? please
